export async function getFrame(id: number) {
    switch (id) {
        case 1:
            return import('@/assets/images/frames/1.png');
        case 2:
            return import('@/assets/images/frames/2.png');
        case 3:
            return import('@/assets/images/frames/3.png');
        case 4:
            return import('@/assets/images/frames/4.png');
        case 5:
            return import('@/assets/images/frames/5.png');
        case 6:
            return import('@/assets/images/frames/6.png');
        case 7:
            return import('@/assets/images/frames/7.png');
        case 8:
            return import('@/assets/images/frames/8.png');
        case 9:
            return import('@/assets/images/frames/9.png');
        case 10:
            return import('@/assets/images/frames/10.png');
        case 11:
            return import('@/assets/images/frames/11.png');
        case 12:
            return import('@/assets/images/frames/12.png');
        case 13:
            return import('@/assets/images/frames/13.png');
        case 14:
            return import('@/assets/images/frames/14.png');
        case 15:
            return import('@/assets/images/frames/15.png');
        case 16:
            return import('@/assets/images/frames/16.png');
        case 17:
            return import('@/assets/images/frames/17.png');
        case 18:
            return import('@/assets/images/frames/18.png');
        case 19:
            return import('@/assets/images/frames/19.png');
        case 20:
            return import('@/assets/images/frames/20.png');
        case 21:
            return import('@/assets/images/frames/21.png');
        case 22:
            return import('@/assets/images/frames/22.png');
        case 23:
            return import('@/assets/images/frames/23.png');
        case 24:
            return import('@/assets/images/frames/24.png');
        case 25:
            return import('@/assets/images/frames/25.png');
        case 26:
            return import('@/assets/images/frames/26.png');
        case 27:
            return import('@/assets/images/frames/27.png');
        case 28:
            return import('@/assets/images/frames/28.png');
        case 29:
            return import('@/assets/images/frames/29.png');
        case 30:
            return import('@/assets/images/frames/30.png');
        case 31:
            return import('@/assets/images/frames/31.png');
        case 32:
            return import('@/assets/images/frames/32.png');
        case 33:
            return import('@/assets/images/frames/33.png');
        case 34:
            return import('@/assets/images/frames/34.png');
        case 35:
            return import('@/assets/images/frames/35.png');
        case 36:
            return import('@/assets/images/frames/36.png');
        case 37:
            return import('@/assets/images/frames/37.png');
        case 38:
            return import('@/assets/images/frames/38.png');
        case 39:
            return import('@/assets/images/frames/39.png');
        case 40:
            return import('@/assets/images/frames/40.png');
        case 41:
            return import('@/assets/images/frames/41.png');
        default:
            return import('@/assets/images/frames/0.png');
    }
}